package com.kneelawk.wiredredstone.client.render.part

import com.kneelawk.wiredredstone.WRConstants.id
import com.kneelawk.wiredredstone.client.render.*
import com.kneelawk.wiredredstone.part.key.BundledCablePartKey
import net.fabricmc.fabric.api.renderer.v1.mesh.Mesh
import net.minecraft.client.texture.Sprite
import net.minecraft.util.DyeColor.*
import net.minecraft.util.Identifier

object BundledCablePartBaker : AbstractPartBaker<BundledCablePartKey>() {
    override fun makeMesh(key: BundledCablePartKey): Mesh {
        val builder = RenderUtils.MESH_BUILDER
        val emitter = TransformingQuadEmitter.Single(builder.emitter, SideQuadTransform(key.side))

        val sprites = BUNDLED_CABLE_IDS[key.color]!!.lookup()

        WireRendering.emitWire(
            conn = key.connections,
            side = key.side,
            wireHeight = 4f / 16f,
            wireWidth = 6f / 16f,
            topCrossSprite = sprites.topCross,
            topXSprite = sprites.topX,
            topZSprite = sprites.topZ,
            bottomCrossSprite = sprites.bottomCross,
            bottomXSprite = sprites.bottomX,
            bottomZSprite = sprites.bottomZ,
            sideSprite = sprites.lowerSide,
            upperSideSprite = sprites.upperSide,
            cornerTopXSprite = sprites.outerCornerTop,
            cornerTopZSprite = sprites.outerCornerTop,
            cornerSideSprite = sprites.outerCornerLowerSide,
            cornerUpperSideSprite = sprites.outerCornerUpperSide,
            openEndSprite = sprites.end,
            closedEndSprite = sprites.outerCornerTop,
            sideV = 5f / 16f,
            material = WRMaterials.UNPOWERED_MATERIAL,
            emitter = emitter
        )

        return builder.build()
    }

    data class WireIds(
        val topCross: Identifier, val topX: Identifier, val topZ: Identifier, val bottomCross: Identifier,
        val bottomX: Identifier, val bottomZ: Identifier, val lowerSide: Identifier, val upperSide: Identifier,
        val outerCornerLowerSide: Identifier, val outerCornerUpperSide: Identifier, val outerCornerTop: Identifier,
        val end: Identifier
    ) {
        fun lookup(): WireSprites {
            return WireSprites(
                RenderUtils.getBlockSprite(topCross),
                RenderUtils.getBlockSprite(topX),
                RenderUtils.getBlockSprite(topZ),
                RenderUtils.getBlockSprite(bottomCross),
                RenderUtils.getBlockSprite(bottomX),
                RenderUtils.getBlockSprite(bottomZ),
                RenderUtils.getBlockSprite(lowerSide),
                RenderUtils.getBlockSprite(upperSide),
                RenderUtils.getBlockSprite(outerCornerLowerSide),
                RenderUtils.getBlockSprite(outerCornerUpperSide),
                RenderUtils.getBlockSprite(outerCornerTop),
                RenderUtils.getBlockSprite(end)
            )
        }
    }

    data class WireSprites(
        val topCross: Sprite, val topX: Sprite, val topZ: Sprite, val bottomCross: Sprite, val bottomX: Sprite,
        val bottomZ: Sprite, val lowerSide: Sprite, val upperSide: Sprite, val outerCornerLowerSide: Sprite,
        val outerCornerUpperSide: Sprite, val outerCornerTop: Sprite, val end: Sprite
    )

    private val BUNDLED_CABLE_IDS = mapOf(
        null to WireIds(
            id("block/bundled_cable/top_cross"),
            id("block/bundled_cable/top_x"),
            id("block/bundled_cable/top_z"),
            id("block/bundled_cable/bottom_cross"),
            id("block/bundled_cable/bottom_x"),
            id("block/bundled_cable/bottom_z"),
            id("block/bundled_cable/lower_side"),
            id("block/bundled_cable/upper_side"),
            id("block/bundled_cable/outer_corner_lower_side"),
            id("block/bundled_cable/outer_corner_upper_side"),
            id("block/bundled_cable/outer_corner_top"),
            id("block/bundled_cable/end"),
        ),
        WHITE to WireIds(
            id("block/bundled_cable/white/top_cross"),
            id("block/bundled_cable/white/top_x"),
            id("block/bundled_cable/white/top_z"),
            id("block/bundled_cable/white/bottom_cross"),
            id("block/bundled_cable/white/bottom_x"),
            id("block/bundled_cable/white/bottom_z"),
            id("block/bundled_cable/white/lower_side"),
            id("block/bundled_cable/white/upper_side"),
            id("block/bundled_cable/white/outer_corner_lower_side"),
            id("block/bundled_cable/white/outer_corner_upper_side"),
            id("block/bundled_cable/white/outer_corner_top"),
            id("block/bundled_cable/white/end"),
        ),
        ORANGE to WireIds(
            id("block/bundled_cable/orange/top_cross"),
            id("block/bundled_cable/orange/top_x"),
            id("block/bundled_cable/orange/top_z"),
            id("block/bundled_cable/orange/bottom_cross"),
            id("block/bundled_cable/orange/bottom_x"),
            id("block/bundled_cable/orange/bottom_z"),
            id("block/bundled_cable/orange/lower_side"),
            id("block/bundled_cable/orange/upper_side"),
            id("block/bundled_cable/orange/outer_corner_lower_side"),
            id("block/bundled_cable/orange/outer_corner_upper_side"),
            id("block/bundled_cable/orange/outer_corner_top"),
            id("block/bundled_cable/orange/end"),
        ),
        MAGENTA to WireIds(
            id("block/bundled_cable/magenta/top_cross"),
            id("block/bundled_cable/magenta/top_x"),
            id("block/bundled_cable/magenta/top_z"),
            id("block/bundled_cable/magenta/bottom_cross"),
            id("block/bundled_cable/magenta/bottom_x"),
            id("block/bundled_cable/magenta/bottom_z"),
            id("block/bundled_cable/magenta/lower_side"),
            id("block/bundled_cable/magenta/upper_side"),
            id("block/bundled_cable/magenta/outer_corner_lower_side"),
            id("block/bundled_cable/magenta/outer_corner_upper_side"),
            id("block/bundled_cable/magenta/outer_corner_top"),
            id("block/bundled_cable/magenta/end"),
        ),
        LIGHT_BLUE to WireIds(
            id("block/bundled_cable/light_blue/top_cross"),
            id("block/bundled_cable/light_blue/top_x"),
            id("block/bundled_cable/light_blue/top_z"),
            id("block/bundled_cable/light_blue/bottom_cross"),
            id("block/bundled_cable/light_blue/bottom_x"),
            id("block/bundled_cable/light_blue/bottom_z"),
            id("block/bundled_cable/light_blue/lower_side"),
            id("block/bundled_cable/light_blue/upper_side"),
            id("block/bundled_cable/light_blue/outer_corner_lower_side"),
            id("block/bundled_cable/light_blue/outer_corner_upper_side"),
            id("block/bundled_cable/light_blue/outer_corner_top"),
            id("block/bundled_cable/light_blue/end"),
        ),
        YELLOW to WireIds(
            id("block/bundled_cable/yellow/top_cross"),
            id("block/bundled_cable/yellow/top_x"),
            id("block/bundled_cable/yellow/top_z"),
            id("block/bundled_cable/yellow/bottom_cross"),
            id("block/bundled_cable/yellow/bottom_x"),
            id("block/bundled_cable/yellow/bottom_z"),
            id("block/bundled_cable/yellow/lower_side"),
            id("block/bundled_cable/yellow/upper_side"),
            id("block/bundled_cable/yellow/outer_corner_lower_side"),
            id("block/bundled_cable/yellow/outer_corner_upper_side"),
            id("block/bundled_cable/yellow/outer_corner_top"),
            id("block/bundled_cable/yellow/end"),
        ),
        LIME to WireIds(
            id("block/bundled_cable/lime/top_cross"),
            id("block/bundled_cable/lime/top_x"),
            id("block/bundled_cable/lime/top_z"),
            id("block/bundled_cable/lime/bottom_cross"),
            id("block/bundled_cable/lime/bottom_x"),
            id("block/bundled_cable/lime/bottom_z"),
            id("block/bundled_cable/lime/lower_side"),
            id("block/bundled_cable/lime/upper_side"),
            id("block/bundled_cable/lime/outer_corner_lower_side"),
            id("block/bundled_cable/lime/outer_corner_upper_side"),
            id("block/bundled_cable/lime/outer_corner_top"),
            id("block/bundled_cable/lime/end"),
        ),
        PINK to WireIds(
            id("block/bundled_cable/pink/top_cross"),
            id("block/bundled_cable/pink/top_x"),
            id("block/bundled_cable/pink/top_z"),
            id("block/bundled_cable/pink/bottom_cross"),
            id("block/bundled_cable/pink/bottom_x"),
            id("block/bundled_cable/pink/bottom_z"),
            id("block/bundled_cable/pink/lower_side"),
            id("block/bundled_cable/pink/upper_side"),
            id("block/bundled_cable/pink/outer_corner_lower_side"),
            id("block/bundled_cable/pink/outer_corner_upper_side"),
            id("block/bundled_cable/pink/outer_corner_top"),
            id("block/bundled_cable/pink/end"),
        ),
        GRAY to WireIds(
            id("block/bundled_cable/gray/top_cross"),
            id("block/bundled_cable/gray/top_x"),
            id("block/bundled_cable/gray/top_z"),
            id("block/bundled_cable/gray/bottom_cross"),
            id("block/bundled_cable/gray/bottom_x"),
            id("block/bundled_cable/gray/bottom_z"),
            id("block/bundled_cable/gray/lower_side"),
            id("block/bundled_cable/gray/upper_side"),
            id("block/bundled_cable/gray/outer_corner_lower_side"),
            id("block/bundled_cable/gray/outer_corner_upper_side"),
            id("block/bundled_cable/gray/outer_corner_top"),
            id("block/bundled_cable/gray/end"),
        ),
        LIGHT_GRAY to WireIds(
            id("block/bundled_cable/light_gray/top_cross"),
            id("block/bundled_cable/light_gray/top_x"),
            id("block/bundled_cable/light_gray/top_z"),
            id("block/bundled_cable/light_gray/bottom_cross"),
            id("block/bundled_cable/light_gray/bottom_x"),
            id("block/bundled_cable/light_gray/bottom_z"),
            id("block/bundled_cable/light_gray/lower_side"),
            id("block/bundled_cable/light_gray/upper_side"),
            id("block/bundled_cable/light_gray/outer_corner_lower_side"),
            id("block/bundled_cable/light_gray/outer_corner_upper_side"),
            id("block/bundled_cable/light_gray/outer_corner_top"),
            id("block/bundled_cable/light_gray/end"),
        ),
        CYAN to WireIds(
            id("block/bundled_cable/cyan/top_cross"),
            id("block/bundled_cable/cyan/top_x"),
            id("block/bundled_cable/cyan/top_z"),
            id("block/bundled_cable/cyan/bottom_cross"),
            id("block/bundled_cable/cyan/bottom_x"),
            id("block/bundled_cable/cyan/bottom_z"),
            id("block/bundled_cable/cyan/lower_side"),
            id("block/bundled_cable/cyan/upper_side"),
            id("block/bundled_cable/cyan/outer_corner_lower_side"),
            id("block/bundled_cable/cyan/outer_corner_upper_side"),
            id("block/bundled_cable/cyan/outer_corner_top"),
            id("block/bundled_cable/cyan/end"),
        ),
        PURPLE to WireIds(
            id("block/bundled_cable/purple/top_cross"),
            id("block/bundled_cable/purple/top_x"),
            id("block/bundled_cable/purple/top_z"),
            id("block/bundled_cable/purple/bottom_cross"),
            id("block/bundled_cable/purple/bottom_x"),
            id("block/bundled_cable/purple/bottom_z"),
            id("block/bundled_cable/purple/lower_side"),
            id("block/bundled_cable/purple/upper_side"),
            id("block/bundled_cable/purple/outer_corner_lower_side"),
            id("block/bundled_cable/purple/outer_corner_upper_side"),
            id("block/bundled_cable/purple/outer_corner_top"),
            id("block/bundled_cable/purple/end"),
        ),
        BLUE to WireIds(
            id("block/bundled_cable/blue/top_cross"),
            id("block/bundled_cable/blue/top_x"),
            id("block/bundled_cable/blue/top_z"),
            id("block/bundled_cable/blue/bottom_cross"),
            id("block/bundled_cable/blue/bottom_x"),
            id("block/bundled_cable/blue/bottom_z"),
            id("block/bundled_cable/blue/lower_side"),
            id("block/bundled_cable/blue/upper_side"),
            id("block/bundled_cable/blue/outer_corner_lower_side"),
            id("block/bundled_cable/blue/outer_corner_upper_side"),
            id("block/bundled_cable/blue/outer_corner_top"),
            id("block/bundled_cable/blue/end"),
        ),
        BROWN to WireIds(
            id("block/bundled_cable/brown/top_cross"),
            id("block/bundled_cable/brown/top_x"),
            id("block/bundled_cable/brown/top_z"),
            id("block/bundled_cable/brown/bottom_cross"),
            id("block/bundled_cable/brown/bottom_x"),
            id("block/bundled_cable/brown/bottom_z"),
            id("block/bundled_cable/brown/lower_side"),
            id("block/bundled_cable/brown/upper_side"),
            id("block/bundled_cable/brown/outer_corner_lower_side"),
            id("block/bundled_cable/brown/outer_corner_upper_side"),
            id("block/bundled_cable/brown/outer_corner_top"),
            id("block/bundled_cable/brown/end"),
        ),
        GREEN to WireIds(
            id("block/bundled_cable/green/top_cross"),
            id("block/bundled_cable/green/top_x"),
            id("block/bundled_cable/green/top_z"),
            id("block/bundled_cable/green/bottom_cross"),
            id("block/bundled_cable/green/bottom_x"),
            id("block/bundled_cable/green/bottom_z"),
            id("block/bundled_cable/green/lower_side"),
            id("block/bundled_cable/green/upper_side"),
            id("block/bundled_cable/green/outer_corner_lower_side"),
            id("block/bundled_cable/green/outer_corner_upper_side"),
            id("block/bundled_cable/green/outer_corner_top"),
            id("block/bundled_cable/green/end"),
        ),
        RED to WireIds(
            id("block/bundled_cable/red/top_cross"),
            id("block/bundled_cable/red/top_x"),
            id("block/bundled_cable/red/top_z"),
            id("block/bundled_cable/red/bottom_cross"),
            id("block/bundled_cable/red/bottom_x"),
            id("block/bundled_cable/red/bottom_z"),
            id("block/bundled_cable/red/lower_side"),
            id("block/bundled_cable/red/upper_side"),
            id("block/bundled_cable/red/outer_corner_lower_side"),
            id("block/bundled_cable/red/outer_corner_upper_side"),
            id("block/bundled_cable/red/outer_corner_top"),
            id("block/bundled_cable/red/end"),
        ),
        BLACK to WireIds(
            id("block/bundled_cable/black/top_cross"),
            id("block/bundled_cable/black/top_x"),
            id("block/bundled_cable/black/top_z"),
            id("block/bundled_cable/black/bottom_cross"),
            id("block/bundled_cable/black/bottom_x"),
            id("block/bundled_cable/black/bottom_z"),
            id("block/bundled_cable/black/lower_side"),
            id("block/bundled_cable/black/upper_side"),
            id("block/bundled_cable/black/outer_corner_lower_side"),
            id("block/bundled_cable/black/outer_corner_upper_side"),
            id("block/bundled_cable/black/outer_corner_top"),
            id("block/bundled_cable/black/end"),
        )
    )
}
